controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

calctoolindex:
    path: /calctool/index
    controller: App\Controller\CalculationToolController::index

calctoolnew:
    path: /calctool/new
    controller: App\Controller\CalculationToolController::new