controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

calculationtool:
    path: /calctool/index
    controller: App\Controller\CalculationToolController::index