controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

homepage:
    path: /
    controller: App\Controller\CalculationToolController::calculation

calculation:
    path: /calculation
    controller: App\Controller\CalculationToolController::calculation

index:
    path: /index
    controller: App\Controller\CalculationToolController::index