# config/validator/validation.yaml
App\Entity\CalculationToolForm:
  properties:
    vehiclePrice:
      - NotBlank: ~
    vehicleType:
      - NotBlank: ~
      - Choice: { choices: [Common, Luxury] }